sudo: required
dist: trusty
env:
  global:
  #- TEXMFLOCAL=/tmp/texmf/
before_install:
- cd tse-paper
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk latex-xcolor pgf
- tlmgr install tcolorbox
#- wget -q http://mirrors.ctan.org/macros/latex/contrib/tcolorbox.zip
#- unzip -qq tcolorbox.zip    -d $TEXMFLOCAL
#- texhash
script:
- make
deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
  - paper.pdf
  skip_cleanup: true
  on:
    tags: true
