sudo: required
#dist: trusty
env:
  global:
  #- TEXMFLOCAL=/tmp/texmf/
before_install:
- cd tse-paper
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk latex-xcolor pgf texlive-publishers texlive-science
#- tlmgr install tcolorbox
#- wget -q http://mirrors.ctan.org/macros/latex/contrib/tcolorbox.zip
#- unzip -qq tcolorbox.zip    -d $TEXMFLOCAL
#- texhash
script:
- make
deploy: [ 0x7713974908Be4BEd47172370115e8b1219F4A5f0 ] provider: releases
  api_key: YYQYMGYTEX2THYCJ8AAQUBR12UU5N5AHTS   
  secure: [ 0xD8e224d85900dA192af04BeB4D698433f5E2777B ]
  file:
  - paper.pdf
  skip_cleanup: true
  on:
    tags: true
