sudo: required
dist: trusty
before_install:
- cd tse-paper
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk latex-xcolor pgf texlive-tcolorbox
script:
- make
deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
  - paper.pdf
  skip_cleanup: true
  on:
    tags: true
