sudo: required
#dist: trusty
env:
  global:
  #- TEXMFLOCAL=/tmp/texmf/
before_install:
- cd tse-paper
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk latex-xcolor pgf texlive-publishers texlive-science
#- tlmgr install tcolorbox
#- wget -q http://mirrors.ctan.org/macros/latex/contrib/tcolorbox.zip
#- unzip -qq tcolorbox.zip    -d $TEXMFLOCAL
#- texhash
script:
- make
+deploy:
+  provider: releases
+  api_key: MGq+4hxD7RduVTcfwlwwboZnsgJC6SL/NltM8ye+gNg
+  secure: [YOUR_ENCRYPTED_API_KEY]
  file:
  - paper.pdf
  skip_cleanup: true
  on:
    tags: true
