repo_selection:
  languages: 1 #30
  repos_per_language: 1 #3
  repos_to_try_per_language: 15 #15
  batch_size: 5

log_selection:
  total_log_count: 1000 #30
  log_count_per_state: 200 #3
  try_count: 2000

auth:
  travis_token: wnjJqxnQHvEnxu_ZI5bAXA