repo_selection:
  languages: 30 #30
  repos_per_language: 3 #3
  repos_to_try_per_language: 15 #15
  batch_size: 5

log_selection:
  total_log_count: 12 #30
  log_count_per_state: 2 #3
  try_count: 100

auth:
  travis_token: wnjJqxnQHvEnxu_ZI5bAXA