repo_selection:
  languages: 30
  repos_per_language: 3
  repos_to_try_per_language: 15
  batch_size: 5

log_selection:
  total_log_count: 60 # there seem to be at max. 6 states so 6 * log_count_per_state is enough
  log_count_per_state: 10
  try_count: 1000

auth:
  travis_token: <insert your travis API token!>