repo_selection:
  languages: 3 #30
  repos_per_language: 1 #3
  repos_to_try_per_language: 5 #15
  batch_size: 5

log_selection:
  total_log_count: 3 #15
  log_count_per_state: 1 #5

auth:
  travis_token: wnjJqxnQHvEnxu_ZI5bAXA